#ifndef _DIS_CONFIG_H_
#define _DIS_CONFIG_H_

#define DIS_CHAR_SYSTEM_ID_SUPPORT
#define DIS_CHAR_MODEL_NUMBER_SUPPORT
#define DIS_CHAR_SERIAL_NUMBER_SUPPORT
#define DIS_CHAR_FIRMWARE_REVISION_SUPPORT
#define DIS_CHAR_HARDWARE_REVISION_SUPPORT
#define DIS_CHAR_SOFTWARE_REVISION_SUPPORT
#define DIS_CHAR_MANUFACTURER_NAME_SUPPORT
#define DIS_CHAR_IEEE_CERTIF_DATA_LIST_SUPPORT
#define DIS_CHAR_PNP_ID_SUPPORT

#ifdef DIS_CHAR_MODEL_NUMBER_SUPPORT
#define DIS_CHAR_MODEL_NUMBER_STR_MAX_LENGTH            20
#endif

#ifdef DIS_CHAR_SERIAL_NUMBER_SUPPORT
#define DIS_CHAR_SERIAL_NUMBER_STR_MAX_LENGTH           20
#endif

#ifdef DIS_CHAR_FIRMWARE_REVISION_SUPPORT
#define DIS_CHAR_FIRMWARE_REVISION_STR_MAX_LENGTH   20
#endif

#ifdef DIS_CHAR_HARDWARE_REVISION_SUPPORT
#define DIS_CHAR_HARDWARE_REVISION_STR_MAX_LENGTH   20
#endif

#ifdef DIS_CHAR_SOFTWARE_REVISION_SUPPORT
#define DIS_CHAR_SOFTWARE_REVISION_STR_MAX_LENGTH   20
#endif

#ifdef DIS_CHAR_MANUFACTURER_NAME_SUPPORT
#define DIS_CHAR_MANUFACTURER_NAME_STR_MAX_LENGTH  20
#endif

#ifdef DIS_CHAR_IEEE_CERTIF_DATA_LIST_SUPPORT
#define DIS_CHAR_IEEE_CERTIF_DATA_LIST_MAX_LENGTH  30
#endif

#define GATT_SVC_DIS_MANU_NAME_INDEX        2
#define GATT_SVC_DIS_MODEL_NUM_INDEX        4
#define GATT_SVC_DIS_SERIAL_NUM_INDEX       6
#define GATT_SVC_DIS_HARDWARE_REV_INDEX     8
#define GATT_SVC_DIS_FIRMWARE_REV_INDEX     10
#define GATT_SVC_DIS_SOFTWARE_REV_INDEX     12
#define GATT_SVC_DIS_SYSTEM_ID_INDEX        14
#define GATT_SVC_DIS_IEEE_CERT_STR_INDEX    16
#define GATT_SVC_DIS_PNP_ID_INDEX           18

#endif
