
#ifndef _HTS_CONFIG_H
#define _HTS_CONFIG_H

#define HTS_TEMPERATURE_TYPE_CHAR_SUPPORT
#define HTS_INTERMEDIATE_TEMPERATURE_CHAR_SUPPORT
#define HTS_MEASUREMENT_INTERVAL_CHAR_SUPPORT
#define HTS_MEASUREMENT_INTERVAL_CHAR_INDICATE_SUPPORT
#define HTS_MEASUREMENT_INTERVAL_CHAR_WRITE_SUPPORT


#define HTS_TEMPERATURE_MEASUREMENT_INDEX                   2
#define HTS_TEMPERATURE_TYPE_INDEX                          5
#define HTS_INTERMEDIATE_TEMPERATURE_INDEX                  7
#define HTS_MEASUREMENT_INTERVAL_INDEX                      10
#define HTS_MEASUREMENT_INTERVAL_VALID_RANGE_INDEX          12

#define HTS_TEMPERATURE_MEASUREMENT_CCCD_INDEX              3
#define HTS_INTERMEDIATE_TEMPERATURE_CCCD_INDEX             8
#define HTS_MEASUREMENT_INTERVAL_CCCD_INDEX                 11




#endif
